Changed device registration to use email and AuthKey (instead of location id and password). Moved localIp handling to Network class. Fixed bug with DS18B20 wrong status after lost connection with server. Changed library metafile, so it won't generate warning for EPS8266.
SUPLA/arduino pull request #14
Opened 2019-12-02 23:26 UTC by klew

2019-12-05 17:37 UTC, przemyslawzygmunt requested changes

2019-12-05 17:37 UTC, przemyslawzygmunt commented on libraries/SuplaDevice/examples/SuplaSomfy/SuplaSomfy.ino
> +  // with GUID that you can retrieve from https://www.supla.org/arduino/get-guid
I have created a dedicated url
https://www.supla.org/pl/arduino/get-authkey

2019-12-05 17:37 UTC, przemyslawzygmunt commented on libraries/SuplaDevice/examples/Supla_DHT/Supla_DHT.ino
> +  // with GUID that you can retrieve from https://www.supla.org/arduino/get-guid
I have created a dedicated url
https://www.supla.org/pl/arduino/get-authkey

2019-12-05 17:37 UTC, przemyslawzygmunt commented on libraries/SuplaDevice/examples/Supla_DallasTemperature/Supla_DallasTemperature.ino
> +  // Use the same link as for GUID and generate AuthKey:
I have created a dedicated url
https://www.supla.org/pl/arduino/get-authkey

2019-12-05 17:37 UTC, przemyslawzygmunt commented on libraries/SuplaDevice/examples/Supla_RGBW/Supla_RGBW.ino
> +  // Use the same link as for GUID and generate AuthKey:
I have created a dedicated url
https://www.supla.org/pl/arduino/get-authkey

2019-12-05 17:37 UTC, przemyslawzygmunt commented on libraries/SuplaDevice/examples/Supla_RollerShutter/Supla_RollerShutter.ino
> +  // Use the same link as for GUID and generate AuthKey:
I have created a dedicated url
https://www.supla.org/pl/arduino/get-authkey

2019-12-05 17:37 UTC, przemyslawzygmunt commented on libraries/SuplaDevice/examples/Supla_RollerShutter_FRAM/Supla_RollerShutter_FRAM.ino
> +  // Use the same link as for GUID and generate AuthKey:
I have created a dedicated url
https://www.supla.org/pl/arduino/get-authkey

2019-12-05 17:37 UTC, przemyslawzygmunt commented on readme.md
> +// Generate AUTHKEY from https://www.supla.org/arduino/get-guid
I have created a dedicated url
https://www.supla.org/pl/arduino/get-authkey

2019-12-06 09:38 UTC, merged

2019-12-08 21:45 UTC, klew commented on libraries/SuplaDevice/examples/SuplaSomfy/SuplaSomfy.ino
> +  // with GUID that you can retrieve from https://www.supla.org/arduino/get-guid
This link is to pl version. "get-guid" is without /pl/ and it works. "get-authkey" doesn't work without locale. Could you please create link that will be not assigned to specific language?

2019-12-08 22:15 UTC, przemyslawzygmunt commented on libraries/SuplaDevice/examples/SuplaSomfy/SuplaSomfy.ino
> +  // with GUID that you can retrieve from https://www.supla.org/arduino/get-guid
Done