support for sensors: SHT3x, Si7021, Si7021 for Sonoff
SUPLA/arduino pull request #27
Opened 2020-11-11 16:38 UTC by krycha88

2020-11-11 21:42 UTC, klew requested changes
In case of those sensors, there are common methods to read temperature and humidity from device, so it looks quite strange that we try to read it twice from device (first time in getTime, second in getHumi).
You could override iterateAlways method and put there single "readValuesFromDevice" method which stores temperature and humidity in class variables, then call channel.setNewValue(temperature, humidity); instead of using getTemp and getHumi, which doesn't fit well to those sensors.

2020-11-11 21:42 UTC, klew commented on libraries/SuplaDevice/src/supla/sensor/SHT3x.h
> +#include "ClosedCube_SHT31D.h"
use < > for files which are not in the same folder as compiled file. Apply the same comment to other files

2020-11-11 21:42 UTC, klew commented on libraries/SuplaDevice/src/supla/sensor/Si7021.h
> +    sensor = Adafruit_Si7021();
I think this is not needed and not correct operation. In Si7021 example it is called on a line where object is declared, so it is just explicite call to default constructor. In your case there is assignement operator used.

2020-11-11 21:42 UTC, klew commented on libraries/SuplaDevice/src/supla/sensor/Si7021_sonoff.h
> +    delay(100);
Move those operations to "onInit" method

2020-11-11 21:42 UTC, klew commented on libraries/SuplaDevice/src/supla/sensor/Si7021_sonoff.h
> +  }
please don't copy bad examples ;). This method is already implemented properly in base class, so you can remove it from here completely.

2020-11-11 21:42 UTC, klew commented on libraries/SuplaDevice/src/supla/sensor/Si7021_sonoff.h
> +    d[0] = d[1] = d[2] = d[3] = d[4] = 0;
you can init it with nulls via:
uint8_t d[5] = {0};
or
uint8_t d[5] = {};

2020-11-12 21:44 UTC, klew commented
Thanks for changes. I'm ok with accepting this PR.

2020-11-13 12:41 UTC, klew commented on libraries/SuplaDevice/src/supla/sensor/MAX6675_K.cpp
> +    return -111;
Why -111? Maybe TEMPERATURE_NOT_AVAILABLE will be better here.

2020-11-13 13:53 UTC, klew commented
👍

2020-11-14 11:15 UTC, ermaya commented
The idea was to show that the connection between Max6675 and the probe is interrupted "open circuit" as a reference to the user.
As the reading range is from 0º to 1014º any negative value could be used for this.

2021-01-09 22:22 UTC, merged